version: "3"
services:
    mysql57:
        image: mysql:5.7
        container_name: mysql57
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: temporalPassword!
            MYSQL_USER: appUser
            MYSQL_PASSWORD: pass123!
            MYSQL_DATABASE: student_course_enrollment
        healthcheck:
            test: "/etc/init.d/mysql status"
            interval: 1s
            retries: 10
        volumes:
            - ./schema-mysql-data.sql:/docker-entrypoint-initdb.d/setup.sql
#            - db_data:/var/lib/mysql
    webapp:
        build: .
        ports:
            - 8080:8080
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysql57:3306/student_course_enrollment?useSSL=false",
                "spring.datasource.username" : "appUser",
                "spring.datasource.password" : "pass123!",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
            }'
        depends_on:
            mysql57:
                condition: service_healthy
